Common:
 Image_repo: imageacr.azurecr.io/
 Vault_token: "s.0Pv176XQ8RCiPtVWxy1aj5Sd"
firstapp:
  Image: himani2203/springbootmavenjunitsample
  Tag: #{Release.Artifacts._java-app.BuildId}#
secondapp:
  Image: himani2203/spring-boot-maven-example-helloworld
  Tag: #{Release.Artifacts._hello-world-app.BuildId}#
