apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: java-deploy
spec: 
  selector: 
    matchLabels: 
      app: java 
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template:
    metadata:
      labels:
        app: java
    spec: 
     containers: 
      - name: java
        image: {{ .Values.Common.Image_repo }}{{ .Values.firstapp.Image }}:{{ .Values.firstapp.Tag }}
        ports: 
        - containerPort: 8080
     imagePullSecrets:
      - name: autodeploy      
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: java-ser
spec: 
  selector: 
    app: java 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
  type: LoadBalancer 
---
